baseurl = "https://dirkkelly.com/"
languageCode = "en-us"
title = "Dirk Kelly"
theme = "hyde"
metadataformat = "yaml"
canonifyurls = true
googleAnalytics = "UA-38004449-5"

[taxonomies]
   tag = "tags"

[params]
  author = "dirkkelly"
  description = "Human Australian Technologist living in America"

  themeColor = "theme-base-0d"

[[menu.main]]
    name = "Résumé"
    url = "/resume/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 2
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 2
[[menu.tags]]
    name = "America"
    url = "/tags/america"
    weight = 2
[[menu.tags]]
    name = "Noam Chomsky"
    url = "/tags/noam-chomsky"
    weight = 2
[[menu.tags]]
    name = "Derrick Jensen"
    url = "/tags/derrick-jensen"
    weight = 2
[[menu.tags]]
    name = "Donald Trump"
    url = "/tags/donald-trump"
    weight = 2
