baseURL = "https://dirkkelly.com/"
canonifyurls = true
googleAnalytics = "UA-38004449-5"
languageCode = "en-us"
metadataformat = "yaml"
title = "Dirk Kelly"
# disqusshortname = "dirkkellycom"
staticman_api = "https://api.staticman.net/v2/entry/dirkkelly/dirkkelly/master/comments"
pluralizelisttitles = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "dirkkelly"
  logo = "/images/dirkkelly.jpg"
  description = "Thinking about politics, economics, and technology during humanity's struggle to navigate the collapse of Capitalism and subsequent Holocene extinction."

[[menu.navbar]]
  name = "Essays"
  url = "/essays/"
  identifier = "essay"
  weight = "1"

[[menu.navbar]]
  name = "Blog"
  url = "/blog/"
  identifier = "blog"
  weight = "2"

[[menu.navbar]]
  name = "Media"
  url = "/media/"
  identifier = "media"
  weight = "3"

[[menu.sidebar]]
  name = "Resumé"
  url = "/resume/"
  identifier = "resume"
  weight = "1"

[[menu.sidebar]]
  name = "About"
  url = "/about/"
  identifier = "about"
  weight = "2"

[[menu.sidebar]]
  name = "Contact"
  url = "/contact/"
  identifier = "contact"
  weight = "3"

[[menu.navbar_right]]
  name = "Youtube"
  url = "https://youtube.com/dirkkelly"
  identifier = "youtube"
  weight = "2"

[[menu.navbar_right]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/dirk-kelly"
  identifier = "linkedin"
  weight = "4"

[permalinks]
  channels = "/:filename"

[taxonomies]
  tag = "tags"
