baseUrl = "https://dirkkelly.com/"
canonifyurls = true
googleAnalytics = "UA-38004449-5"
languageCode = "en-us"
metadataformat = "yaml"
title = "Dirk Kelly"
# disqusshortname = "dirkkellycom"
staticman_api = "https://api.staticman.net/v2/entry/dancwilliams/networkhobo/master/comments"
pluralizelisttitles = false
SectionPagesMenu = "topbar"

[params]
  author = "dirkkelly"
  description = "Austramerican thinking about politics, economics, and technology during humanity's struggle to survive the collapse of capitalism and holocene extinction."

[[menu.sidebar]]
  name = "Subscribe"
  url = "/index.xml"
  weight = 4

[[menu.topbar]]
  name = "Politics"
  url = "/politics/"
  identifier = "politics"
  weight = 1

[[menu.topbar]]
  name = "Economics"
  url = "/economics/"
  identifier = "economics"
  weight = 2

[[menu.topbar]]
  name = "Technology"
  url = "/technology/"
  identifier = "technology"
  weight = 3

[[menu.topbar]]
  name = "Philosophy"
  url = "/philosophy/"
  identifier = "philosophy"
  weight = 4

[[menu.topbar]]
  name = "Survive"
  url = "/survive/"
  identifier = "survive"
  weight = 5

[[menu.topbar]]
  name = "Collapse"
  url = "/collapse/"
  identifier = "collapse"
  weight = 6

[[menu.topbar]]
  identifier = "channels"

[[menu.topbar]]
  identifier = "redirects"

[permalinks]
  channels = "/:filename"

[taxonomies]
  tag = "tags"
