baseURL = "https://dirkkelly.com/"
canonifyurls = true
googleAnalytics = "UA-38004449-5"
languageCode = "en-us"
metadataformat = "yaml"
title = "Dirk Kelly"
# disqusshortname = "dirkkellycom"
staticman_api = "https://api.staticman.net/v2/entry/dirkkelly/dirkkelly/master/comments"
pluralizelisttitles = false

[params]
  author = "dirkkelly"
  description = "Thinking about politics, economics, and technology during humanity's struggle to navigate the collapse of Capitalism and subsequent Holocene extinction."

[[menu.topbar]]
  name = "Politics"
  url = "/politics/"
  identifier = "politics"
  weight = 1

[[menu.topbar]]
  name = "Economics"
  url = "/economics/"
  identifier = "economics"
  weight = 2

[[menu.topbar]]
  name = "Technology"
  url = "/technology/"
  identifier = "technology"
  weight = 3

[[menu.topbar]]
  name = "Philosophy"
  url = "/philosophy/"
  identifier = "philosophy"
  weight = 4

[[menu.topbar]]
  name = "Survive"
  url = "/survive/"
  identifier = "survive"
  weight = 5

[[menu.topbar]]
  name = "Collapse"
  url = "/collapse/"
  identifier = "collapse"
  weight = 6

[[menu.topbar]]
  identifier = "channels"

[[menu.topbar]]
  identifier = "redirects"

[[menu.sidebar]]
  name = "Essays"
  url = "/essays/"
  identifier = "essays"
  weight = "1"

[[menu.sidebar]]
  name = "Blog"
  url = "/blog/"
  identifier = "blog"
  weight = "2"

[[menu.sidebar]]
  name = "Media"
  url = "/media/"
  identifier = "media"
  weight = "4"

[[menu.sidebar]]
  name = "Videos"
  url = "/videos/"
  identifier = "videos"
  weight = "5"

[[menu.sidebar]]
  name = "Youtube"
  url = "https://youtube.com/dirkkelly"
  identifier = "youtube"
  weight = "6"

[[menu.sidebar]]
  name = "Career"
  url = "/career/"
  identifier = "career"
  weight = "7"

[[menu.sidebar]]
  name = "Contact"
  url = "/contact/"
  identifier = "contact"
  weight = "6"

[permalinks]
  channels = "/:filename"

[taxonomies]
  tag = "tags"
