baseurl = "https://dirkkelly.com/"
languageCode = "en-us"
title = "Dirk Kelly"
theme = "hyde"
metadataformat = "yaml"
canonifyurls = true
googleAnalytics = "UA-38004449-5"

[permalinks]
    channels = "/:filename"

[taxonomies]
    tag = "tags"

[params]
    author = "dirkkelly"
    description = "Australian Living in America During the Collapse of Capitalism"

    themeColor = "theme-base-au"

[[menu.meta]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.meta]]
    name = "Contact"
    url = "/contact/"
    weight = 2
[[menu.meta]]
    name = "Résumé"
    url = "/resume/"
    weight = 3
[[menu.meta]]
    name = "RSS"
    url = "/index.xml"
    weight = 4
