baseurl = "https://dirkkelly.com/"
languageCode = "en-us"
title = "Dirk Kelly"
theme = "hyde"
metadataformat = "yaml"
canonifyurls = true
googleAnalytics = "UA-38004449-5"

[taxonomies]
   tag = "tags"

[params]
  author = "dirkkelly"
  description = "Australian Technologist living in New York"

  themeColor = "theme-base-0d"

[[menu.main]]
    name = "Résumé"
    url = "/resume/"
    weight = -100
