baseUrl = "https://dirkkelly.com/"
canonifyurls = true
googleAnalytics = "UA-38004449-5"
languageCode = "en-us"
metadataformat = "yaml"
title = "Dirk Kelly"
disqusshortname = "dirkkellycom"
pluralizelisttitles = false

[params]
  author = "dirkkelly"
  description = "Ameristralian writing throughout the collapse of Capitalism and humanity's struggle to survive the Holocene extinction."

[[menu.sidebar]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.sidebar]]
  name = "Career"
  url = "/career/"
  weight = 2

[[menu.sidebar]]
  name = "Contact"
  url = "/contact/"
  weight = 3

[[menu.sidebar]]
  name = "Subscribe"
  url = "/index.xml"
  weight = 4

[[menu.topbar]]
  name = "Philosophy"
  url = "/philosophy/"
  weight = 1

[[menu.topbar]]
  name = "Politics"
  url = "/politics/"
  weight = 2

[[menu.topbar]]
  name = "Economics"
  url = "/economics/"
  weight = 3

[[menu.topbar]]
  name = "Technology"
  url = "/technology/"
  weight = 4

[[menu.topbar]]
  name = "Collapse"
  url = "/collapse/"
  weight = 5

[permalinks]
  channels = "/:filename"

[taxonomies]
  tag = "tags"
