baseurl = "https://dirkkelly.com/"
languageCode = "en-us"
title = "Dirk Kelly"
theme = "hyde"
metadataformat = "yaml"
canonifyurls = true
googleAnalytics = "UA-38004449-5"

[taxonomies]
   tag = "tags"

[params]
  author = "dirkkelly"
  description = "Australian Living in America During the Collapse of Capitalism"

  themeColor = "theme-base-0d"

[[menu.resist]]
    name = "Resist"
    url = "/tags/resist"
    weight = 1
[[menu.resist]]
    name = "Noam Chomsky"
    url = "/tags/noam-chomsky"
    weight = 3
[[menu.resist]]
    name = "Derrick Jensen"
    url = "/tags/derrick-jensen"
    weight = 4
[[menu.resist]]
    name = "Adam Curtis"
    url = "/tags/adam-curtis"
    weight = 5

[[menu.empire]]
    name = "America"
    url = "/tags/america"
    weight = 2
[[menu.empire]]
    name = "Donald Trump"
    url = "/tags/donald-trump"
    weight = 6

[[menu.meta]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.meta]]
    name = "Contact"
    url = "/contact/"
    weight = 2
[[menu.meta]]
    name = "Résumé"
    url = "/resume/"
    weight = 3
[[menu.meta]]
    name = "RSS"
    url = "/index.xml"
    weight = 4
