baseUrl = "https://dirkkelly.com/"
canonifyurls = true
googleAnalytics = "UA-38004449-5"
languageCode = "en-us"
metadataformat = "yaml"
theme = "dirkkelly"
title = "Dirk Kelly"

[params]
  author = "dirkkelly"
  description = "Ameristralian writing throughout the collapse of Capitalism and humanity's struggle to survive the Holocene extinction."
  disqusshortname = "dirkkellycom"

[[menu.meta]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.meta]]
  name = "Career"
  url = "/career/"
  weight = 2

[[menu.meta]]
  name = "Contact"
  url = "/contact/"
  weight = 3

[[menu.meta]]
  name = "Subscribe"
  url = "/index.xml"
  weight = 4

#[[menu.tags]]
#  name = "Noam Chomsky"
#  url = "/tags/noam-chomsky/"
#  weight = 1

[permalinks]
  channels = "/:filename"

[taxonomies]
  tag = "tags"
