baseurl = "https://dirkkelly.com/"
languageCode = "en-us"
title = "Dirk Kelly"
theme = "hyde"
metadataformat = "yaml"
canonifyurls = true
googleAnalytics = "UA-38004449-5"
disqusShortname = "dirkkellycom"

[permalinks]
    channels = "/:filename"

[taxonomies]
    tag = "tags"

[params]
    author = "dirkkelly"
    description = "Australian writing during the collapse of Capitalism and humanity's struggle to survive the Holocene extinction."

    themeColor = "theme-base-au"

[[menu.meta]]
    name = "Channels"
    url = "/channels/"
    weight = 1
[[menu.meta]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.meta]]
    name = "Contact"
    url = "/contact/"
    weight = 3
[[menu.meta]]
    name = "Résumé"
    url = "/resume/"
    weight = 4
[[menu.meta]]
    name = "RSS"
    url = "/index.xml"
    weight = 5

[[menu.tags]]
    name = "Philosophy"
    url = "/tags/philosophy/"
    weight = 1

[[menu.tags]]
    name = "Culture War"
    url = "/tags/culture-war/"
    weight = 2

[[menu.tags]]
    name = "Contrapoints"
    url = "/tags/contrapoints/"
    weight = 3

[[menu.tags]]
    name = "Derrick Jensen"
    url = "/tags/derrick-jensen/"
    weight = 4

[[menu.tags]]
    name = "Noam Chomsky"
    url = "/tags/noam-chomsky/"
    weight = 5
