baseurl = "https://dirkkelly.com"
languageCode = "en-us"
title = "Dirk Kelly"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-38004449-5"

[params]
  # General information
  author = "dirkkelly"
  description = "Another Human, Australian, Socialist, Technologist, Executive, living in Perth and New York"
  copyright = "Released under the MIT license"

  # Repository
  provider = "GitHub"
  repo_url = "https://github.com/dirkkelly/dirkkelly"

  version = "27.10.0"
  logo = "/images/logo.png"
  favicon = "favicon.ico"

  permalink = "#"

  # Custom assets
  custom_css = []
  custom_js  = []

  # Syntax highlighting theme
  highlight_css  = ""

  [params.palette]
      primary = "blue-grey"
      accent  = "teal"

    [params.font]
      text = "Ubuntu"
      code = "Ubuntu Mono"

[social]
  twitter = ""
  github  = "dirkkelly"
  email   = ""

[[menu.main]]
  name   = "Dirk Kelly"
  url    = "/"
  weight = 0

[blackfriday]
  smartypants = true
  fractions = true
  smartDashes = true
  plainIDAnchors = true
