baseUrl = "https://dirkkelly.com/"
canonifyurls = true
googleAnalytics = "UA-38004449-5"
languageCode = "en-us"
metadataformat = "yaml"
theme = "dirkkelly"
title = "Dirk Kelly"

[params]
  author = "dirkkelly"
  description = "Ameristralian writing throughout the collapse of Capitalism and humanity's struggle to survive the Holocene extinction."
  disqusshortname = "dirkkellycom"

[[menu.meta]]
  name = "RSS"
  url = "/index.xml"
  weight = 5

[[menu.meta]]
  name = "Résumé"
  url = "/resume/"
  weight = 4

[[menu.meta]]
  name = "Contact"
  url = "/contact/"
  weight = 3

[[menu.meta]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.meta]]
  name = "Channels"
  url = "/channels/"
  weight = 1

[[menu.tags]]
  name = "Super Deluxe"
  url = "/tags/super-deluxe/"
  weight = 4

[[menu.tags]]
  name = "Friendly Jordies"
  url = "/tags/friendly-jordies/"
  weight = 3

[[menu.tags]]
  name = "Contrapoints"
  url = "/tags/contrapoints/"
  weight = 1

[[menu.tags]]
  name = "Noam Chomsky"
  url = "/tags/noam-chomsky/"
  weight = 2

[permalinks]
  channels = "/:filename"

[taxonomies]
  tag = "tags"
