---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- path: content/economics
  label: Economics
  create: all
- path: content/politics
  label: Politics
  create: all
- path: content/technology
  label: Technology
  create: all
- path: content/collapse
  label: Collapse
  create: all
- path: content/philosophy
  label: Philosophy
  create: all
- path: content/blog
  label: Blog
  create: all
- path: content/essays
  label: Essays
  create: all
  default_front_matter_template: essay
- path: content/media
  label: Media
  create: all
- path: content/videos
  label: Videos
  create: all
- path: content/survive
  label: Survive
  create: all
- path: content/tags
  label: Tags
  create: all
- path: content
  label: Pages
  create: all
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: 0.31.1
