name = "Dirk Kelly"
license = "MIT"
licenselink = "https://github.com/dirkkelly/dirkkelly/blob/master/themes/dirkkelly/LICENSE.md"
description = "A material design theme for documentations."
homepage = "https://github.com/digitalcraftsman/hugo-material-docs"
tags = []
features = ["", ""]
min_version = 0.15

[author]
  name = "Dirkkelly"
  homepage = "https://github.com/dirkkelly"

# If porting an existing theme
[original]
  name = "Digitalcraftsman"
  homepage = "http://themes.gohugo.io/theme/material-docs/"
  repo = "https://github.com/digitalcraftsman/hugo-material-docs"
